## Data config
FRAMES_INTERVAL = 2

### Model config
DIM = 224
IMAGE_SIZE = 224
PATCH_SIZE = 16
NUM_CLASSES = 12
NUM_FRAMES = 32
DEPTH = 6
HEADS = 4
DIM_HEAD = 32
ATTN_DROPOUT = 0.1
FF_DROPOUT = 0.1

### Traning config
MODEL_SAVE_PATH = "checkpoints"
BATCH_SIZE = 8